# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master", "fix/*" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
      
    - name: Make Gradle Wrapper Executable
      run: chmod +x ./gradlew

    - name: Build project
      run: |
        gradle wrapper
        bash gradlew buildPluginLegacy
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: onebot-mirai
        path: build/mirai/OneBot-Mirai-*.mirai.jar
